### ISSUE TITLE
Who owns this repo?

### ISSUE THREAD

**Issue by awslabspl** [temporary-audacity/audacity#80] opened 2021-07-06 16:50 UTC
Who is the `owner` of this repo? Who can give-out privileges?

**Comment by jeyemwey** [comment] 2021-07-06 16:54
There is a small group of people that currently plan the governance. Please hold the line, it takes time and people have other jobs, too.

If you have a real question, please ask it here or in a new issue.

**Comment by awslabspl** [comment] 2021-07-06 16:56
@jeyemwey Thank you :)
All I want is to ask whats their nicknames, because I need to contact them privately.

**Comment by User-green** [comment] 2021-07-06 17:04
This seem to be cookiengineer.

**Comment by awslabspl** [comment] 2021-07-06 17:07
> This seem to be cookiengineer.

I was asking seriously..............

**Comment by jeyemwey** [comment] 2021-07-06 17:08
You are probably looking for Cookie, but they had a rough night and are drowning in messages. So you can probably not reach them right now.

**Comment by awslabspl** [comment] 2021-07-06 17:12
> You are probably looking for Cookie, but they had a rough night and are drowning in messages. So you can probably not reach them right now.

All right but at lease please provide their nickname............

**Comment by peepopoggers** [comment] 2021-07-06 17:30
Idk owners, but moderators -> #48

**Comment by EricBright** [comment] 2021-07-06 17:30
Closed as duplicate of #28.

**Closed by EricBright** 2021-07-06 17:30 UTC
